### ISSUE TITLE
test_names failed on Jenkins

### ISSUE THREAD

**Issue by dqwu** [NCAR/ParallelIO#304]
https://jenkins-ci.mcs.anl.gov/job/ParallelIO_coverage/52/console

The failure was introduced by PR #280.

The newly added function below does not have a return statement at the end
int check_strerror(int my_rank)
{
int ret;
...
}

The returned value is undefined (dependent on the compiler). For code coverage builder, it returns a non-zero value like 1, for other builders they return 0 (the test would pass).

This is similar to issue #163 we fixed before. It looks like code coverage builder is able to find this kind of errors when the return value of a function is undefined.

We need add code coverage builder on develop branch to Jenkins. This way the master branch can be protected from similar bugs in the future.

**Comment by edhartnett** [comment]
This is fixed in the code I just merged to develop. Should be in master as soon as it gets through the next cdash run.

**Comment by dqwu** [comment]
I checked out the latest develop branch and this test still failed with code coverage option turned on.

This is a different issue from #302. You should look at test_name.c, line 285.

**Comment by edhartnett** [comment]
No, that is because I messed up the merge. I have code that fixes both this issue and #302.

But I have to figure out how to get it merged. Probably I will wait until everyone has merged current changes to master, then I will take a new branch from master and try the changes again.

**Comment by edhartnett** [comment]
These fixes have made it to master.

**Comment by edhartnett** [comment]
Actually this change did not make it into master.

I am preparing a pull request now.

**Comment by edhartnett** [comment]
OK, still one case of failure. It happens in the mpiserial build, which does not include pnetcdf.

I have not yet been able to get the mpiserial library to build on my machine. 

I have gotten the C build without pnetcdf to work, and that also allowed me to see the test_names error. And that is fixed on the PR I am about to submit.

**Comment by jedwards4b** [comment]
Mpi-serial should be a very straight forward build - what is the issue there?

**Comment by edhartnett** [comment]
OK, I got the mpiserial library to build and installed it manually.

How to I tell the build where it is?

I am getting this error:

CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find MPISERIAL_C (missing: MPISERIAL_C_LIBRARY
  MPISERIAL_C_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
  cmake/LibFind.cmake:302 (find_package_handle_standard_args)
  cmake/FindMPISERIAL.cmake:40 (find_package_component)
  src/gptl/CMakeLists.txt:98 (find_package)

**Comment by jayeshkrishna** [comment]
Does cmake ... -DMPISERIAL_PATH=<MPI_SERIAL_PATH> ... work for you?

**Comment by edhartnett** [comment]
That helped.

Now it compiles, but all the tests fail...
